### ISSUE TITLE
Translate Section 2: Hooks, useState, useReducer, useEffect, useRef and useImperativeHandle

### ISSUE THREAD

**Issue by GiselaMD** [typescript-cheatsheets/react-pt#5]
Please feel free to ask to work on this issue and I'll assign it to you 😄

https://github.com/typescript-cheatsheets/react#hooks

**Comment by bnrosa** [comment]
Hey, can I get this one? :)

**Comment by GiselaMD** [comment]
Of course @bnrosa !
