### ISSUE TITLE
Translate Section 2: Custom Hooks

### ISSUE THREAD

**Issue by GiselaMD** [typescript-cheatsheets/react-pt#6]
Please feel free to ask to work on this issue and I'll assign it to you 😄

https://github.com/typescript-cheatsheets/react#custom-hooks

**Comment by bnrosa** [comment]
Hey! I'd like to do that one too if that's ok.

**Comment by GiselaMD** [comment]
Sure! Go for it.

**Comment by GiselaMD** [comment]
Closed by #13
